/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileVehicleRouteImport } from './routes/profile.vehicle'
import { Route as ProfileTermsRouteImport } from './routes/profile.terms'
import { Route as ProfileSupportRouteImport } from './routes/profile.support'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileSecurityRouteImport } from './routes/profile.security'
import { Route as ProfileReviewsRouteImport } from './routes/profile.reviews'
import { Route as ProfilePersonalRouteImport } from './routes/profile.personal'
import { Route as DeliveryNewRouteImport } from './routes/delivery.new'
import { Route as DeliveryActiveRouteImport } from './routes/delivery.active'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileVehicleRoute = ProfileVehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileTermsRoute = ProfileTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSupportRoute = ProfileSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileReviewsRoute = ProfileReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePersonalRoute = ProfilePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => ProfileRoute,
} as any)
const DeliveryNewRoute = DeliveryNewRouteImport.update({
  id: '/delivery/new',
  path: '/delivery/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryActiveRoute = DeliveryActiveRouteImport.update({
  id: '/delivery/active',
  path: '/delivery/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/earnings': typeof EarningsRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/delivery/active': typeof DeliveryActiveRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/reviews': typeof ProfileReviewsRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/vehicle': typeof ProfileVehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/earnings': typeof EarningsRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/delivery/active': typeof DeliveryActiveRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/reviews': typeof ProfileReviewsRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/vehicle': typeof ProfileVehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deliveries': typeof DeliveriesRoute
  '/earnings': typeof EarningsRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/pending': typeof PendingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/delivery/active': typeof DeliveryActiveRoute
  '/delivery/new': typeof DeliveryNewRoute
  '/profile/personal': typeof ProfilePersonalRoute
  '/profile/reviews': typeof ProfileReviewsRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/support': typeof ProfileSupportRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/vehicle': typeof ProfileVehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deliveries'
    | '/earnings'
    | '/home'
    | '/onboarding'
    | '/pending'
    | '/profile'
    | '/register'
    | '/signup'
    | '/support'
    | '/delivery/active'
    | '/delivery/new'
    | '/profile/personal'
    | '/profile/reviews'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/support'
    | '/profile/terms'
    | '/profile/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deliveries'
    | '/earnings'
    | '/home'
    | '/onboarding'
    | '/pending'
    | '/profile'
    | '/register'
    | '/signup'
    | '/support'
    | '/delivery/active'
    | '/delivery/new'
    | '/profile/personal'
    | '/profile/reviews'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/support'
    | '/profile/terms'
    | '/profile/vehicle'
  id:
    | '__root__'
    | '/'
    | '/deliveries'
    | '/earnings'
    | '/home'
    | '/onboarding'
    | '/pending'
    | '/profile'
    | '/register'
    | '/signup'
    | '/support'
    | '/delivery/active'
    | '/delivery/new'
    | '/profile/personal'
    | '/profile/reviews'
    | '/profile/security'
    | '/profile/settings'
    | '/profile/support'
    | '/profile/terms'
    | '/profile/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeliveriesRoute: typeof DeliveriesRoute
  EarningsRoute: typeof EarningsRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingRoute: typeof PendingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  DeliveryActiveRoute: typeof DeliveryActiveRoute
  DeliveryNewRoute: typeof DeliveryNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/vehicle': {
      id: '/profile/vehicle'
      path: '/vehicle'
      fullPath: '/profile/vehicle'
      preLoaderRoute: typeof ProfileVehicleRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/terms': {
      id: '/profile/terms'
      path: '/terms'
      fullPath: '/profile/terms'
      preLoaderRoute: typeof ProfileTermsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/support': {
      id: '/profile/support'
      path: '/support'
      fullPath: '/profile/support'
      preLoaderRoute: typeof ProfileSupportRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/reviews': {
      id: '/profile/reviews'
      path: '/reviews'
      fullPath: '/profile/reviews'
      preLoaderRoute: typeof ProfileReviewsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/personal': {
      id: '/profile/personal'
      path: '/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof ProfilePersonalRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/delivery/new': {
      id: '/delivery/new'
      path: '/delivery/new'
      fullPath: '/delivery/new'
      preLoaderRoute: typeof DeliveryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery/active': {
      id: '/delivery/active'
      path: '/delivery/active'
      fullPath: '/delivery/active'
      preLoaderRoute: typeof DeliveryActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfilePersonalRoute: typeof ProfilePersonalRoute
  ProfileReviewsRoute: typeof ProfileReviewsRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSupportRoute: typeof ProfileSupportRoute
  ProfileTermsRoute: typeof ProfileTermsRoute
  ProfileVehicleRoute: typeof ProfileVehicleRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePersonalRoute: ProfilePersonalRoute,
  ProfileReviewsRoute: ProfileReviewsRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSupportRoute: ProfileSupportRoute,
  ProfileTermsRoute: ProfileTermsRoute,
  ProfileVehicleRoute: ProfileVehicleRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeliveriesRoute: DeliveriesRoute,
  EarningsRoute: EarningsRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  PendingRoute: PendingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  DeliveryActiveRoute: DeliveryActiveRoute,
  DeliveryNewRoute: DeliveryNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
